#!/bin/sh
REPO_DIR=$(git rev-parse --show-toplevel)
DOT_GIT_DIR=$(git rev-parse --git-dir)
if [ "$DOT_GIT_DIR" = ".git" ]; then
  DOT_GIT_DIR="$REPO_DIR"/"$DOT_GIT_DIR"
fi
HOOKS_DIR="$DOT_GIT_DIR"/hooks
. "$HOOKS_DIR"/gitflow-functions

source "$HOOKS_DIR/config.sh"

HOOK_ERROR=0

for module in $post_flow_feature_finish_modules; do
    module_path="$HOOKS_MODULES_DIR/$module"
    [ ! $module_path ] && continue
    . "$HOOKS_MODULES_DIR/$module"
    if [ $? -eq 1 ] ; then
        HOOK_ERROR=1
    fi
done

if [ $HOOK_ERROR -eq 1 ] ; then
  echo $'\e[31mPost flow feature modules did not complete successfully... feature finish cancelled\e[0m'
else
  echo $'\e[32mNo errors... feature finished\e[0m'
fi
exit $HOOK_ERROR
